### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by fredol** [Nostrabramus/CookieLawManagement#1] opened 2018-01-24 23:14 UTC
Hello,
We use your extension (great job BTW) and need to use it on multilingual website.
Do you intend to make it easier in the future?
Thank again

**Comment by fredol** [comment] 2018-01-24 23:16
Hello,
We use your extension (great job BTW) and need to use it on multilingual website.
Do you intend to make it easier in the future?
Thank again

**Comment by Nostrabramus** [comment] 2018-01-25 09:28
Hello,
we want our extension to have the best user experience as possible, 
so feedbacks and suggestions are welcome.

The language management is the standard one, to edit messages or add new languages you can edit or add the related .xlf files in the folder aip_cookie_law/Resources/Private/Language/ .

What do you need to make it easier for you to use?
If you explain your needs I can give you information, if we plan to implement them in the near future we need sponsors to fund them.

Regards

Abramo Tesoro
Archimede Informatica

**Comment by FR-95** [comment] 2018-04-24 08:30
Hi @Nostrabramus 

Thank you for this extension.

We have an issue, the translation with the .xlf files isnt working.
We created the file de.locallang.xlf and deleted all caches, no result.


Do you have an idea, where the problem might be?

Thanks!
[de.locallang.txt](https://github.com/Nostrabramus/CookieLawManagement/files/1941670/de.locallang.txt)

**Comment by Nostrabramus** [comment] 2018-04-24 08:51
Hi @DonChef660 
thanks for the tip,
we had already noticed and we are working on it,
today we will upload the changes on the TER and on GitHub

can I use your xlf file to add the german version?
of course we will cite you on documentation

**Comment by FR-95** [comment] 2018-04-24 09:00
Its not perfect, but of course :) and thanks a lot!

**Comment by Nostrabramus** [comment] 2018-04-24 12:33
Hi @DonChef660,
I've just uploaded version 8.7.4 here and on TER (https://extensions.typo3.org/extension/aip_cookie_law/ ), 
now you can correctly use the de.locallang.xlf file

regards

Abramo Tesoro
Archimede Informatica

**Comment by Dari4sho** [comment] 2018-05-09 13:19
Hey all together,
I still have trouble enabling translations. My default page language is german. Nothing configured, I get the english version by default and am not sure where to change or what to adapt to make the magic happen. (I didn't find the solution in the manual)

The de.locallang.xlf exists by default.
Is there something missing in the ConvertXmlToJson.php?

```
if (
    $locallang == 'gb' || $locallang == 'scotland' ||
    $locallang == 'uk' || $locallang == 'england' ||
    $locallang == 'vg' || $locallang == 'wales' ||
    $locallang == 'qc' || $locallang == 'fam' ||
    $locallang == 'vi' || $locallang == 'eu')
```

(Manually adding 'de' / 'germany' didn't help)

I hope you can help me out on this.
Many thanks in advance!

**Comment by Nostrabramus** [comment] 2018-05-09 14:18
Hello

I'm not sure what your _manual attempt_  was

That piece of code gets to bring config.language back to 'en' even in the cases of 'gb', 'uk', 'whales' and so on.
it would not make sense to add in that if statement the 'germany' or 'de' case

if your problem is related to this aspect then you may want to add an additional if:
```
if ($ locallang == 'germany')
        $ locallang = 'de';
```

You already have the xlf file for german language and it has to work by itself!
It works for language = de

can you check your typoscript for language version?
You have to have somenthing like this

```
config {
        sys_language_uid = 0
        language = de
        locale_all = de_DE.UTF-8
        htmlTag_setParams = lang="de" dir="ltr" class="no-js"
}
```

**Comment by instruccionesaldorso** [comment] 2018-05-10 13:51
Hi hi,
We're using your extension as well, but we're facing the same problem for localization of labels.

Analyzing https://github.com/Nostrabramus/CookieLawManagement/blob/master/Classes/UserFunction/ConvertXmlToJson.php class code, I have a few suggestions:
- I guess calling the database, and search for the "flag" field in a "sys_language" record is not the best approach. You avoid the call to the database when the user has no L parameter and use TS setting "config.language". I would say this is a must nowadays. Everyone that configures a TYPO3 website configures this setting properly.
- To avoid calls to "json_encode", I would use another approach. Check the next example how to use the Json view provided by TYPO3: https://github.com/ervaude/json_example

If you need some extra support, just let me know. I can provide a merge request.

**Comment by Nostrabramus** [comment] 2018-05-10 14:57
Hi,
thanks for your advices  
if you want to contribute please go ahead with a pull request and then provide us with your merge

**Comment by instruccionesaldorso** [comment] 2018-05-11 09:12
@Nostrabramus I couldn't push to the repo. Can you give me permissions?

**Comment by Nostrabramus** [comment] 2018-05-11 09:35
@instruccionesaldorso you should have received the invitation

**Comment by Dari4sho** [comment] 2018-05-11 20:07
First of all, thanks a lot for your response and your help.
You're totally right, I was too frenetic to see the context - it would make no sense. This was just a wrong spot on my way to find a solution.

In the meanwhile I moved on to an own implementation inspired by yours which is hardcoded in my Layout since I couldn't make it work, but I can help to resolve this if it's your interest.

My config looks like this
```
config {
    # Config for localization
    sys_language_mode = content_fallback
    sys_language_overlay = hideNonTranslated

    sys_language_uid = 0
    language = de
    htmlTag_langKey = de
    locale_all = de_DE
}
```
I replaced it with your exact example, but no luck, still the english/default output.

Any more ideas? As I've found another solution, it would maybe be better to close this again and see if anyone else faces this problem - just in case it is just me, but I will leave this up to you.

Thanks for your work

**Comment by Nostrabramus** [comment] 2018-05-15 10:17
@instruccionesaldorso many thanks for your contribution, we have accepted your pull request and merged it in the master branch.

**Comment by instruccionesaldorso** [comment] 2018-05-15 14:03
You're welcome, @Nostrabramus ! I didn't have time to answer previous question by @Dari4sho 
Could you make it work?

I wanted to ask something else: as far as I see, there is no possibility to remove the "Tag" shown on the left part (vertical) by default, only the possibility to put it in a different position. Could this be a new feature?
The only way I could remove it is replacing the JavaScript directly.

**Comment by Nostrabramus** [comment] 2018-05-15 15:03
@instruccionesaldorso I moved your question and the answer in another issue:
https://github.com/Nostrabramus/CookieLawManagement/issues/3

**Comment by Nostrabramus** [comment] 2018-05-15 15:19
@Dari4sho your typoscript configuration seems correct to me and should work
I can't reproduce your problem, we tested the extension on a TYPO3 7 and a TYPO3 8 and it works properly

We have just released version 8.7.5 introducing the changes proposed by @instruccionesaldorso, we also modified javascript for a potential conflict with realurl,
so if you want you can update the extension and check if your problem is solved

https://extensions.typo3.org/extension/aip_cookie_law/

Let me know if you've solved it

**Comment by Nostrabramus** [comment] 2018-05-23 12:54
@Dari4sho @DonChef660
The extension works with the standard localization system, ù
so you have only to configure properly your language in your typoscript setup, something like this:

```
config {
       sys_language_uid = 0
       language = de
       locale_all = de_DE.UTF-8
       htmlTag_setParams = lang="de" dir="ltr" class="no-js"
}
```

please note that if you configure your language directly in the template module in the backend you have to add the following lines so the plugin can read the updated language configuration

```
ajaxLanguageJson {
   config {
       language < config.language
       locale_all < config.locale_all
       htmlTag_langKey < config.htmlTag_langKey
       sys_language_uid < config.sys_language_uid    }
   10 < tt_content.list.20.aipcookielaw_cookielaw
}
```
we will add this instructions in the documentation

thanks for your feedback

**Comment by GuidoJansen** [comment] 2018-05-25 11:11
It works for me with this TS setup

```
plugin.tx_aip_cookie_law._LOCAL_LANG {
  default {
    jqueryWarning = Please use jQuery < 1.4.4
    invalidKeyWarning = API not valid
    # ...
  }
  de {
    # ...
  }
}
```

**Comment by Nostrabramus** [comment] 2019-02-15 09:07
Updated the locating mechanism to the new SITE MANAGEMENT module of version 9

**Closed as completed by Nostrabramus** 2019-02-15 09:07 UTC
